### ISSUE TITLE
minor revision

### ISSUE THREAD

**Issue by cproctor** [arcturo/library#12]
In the last sentence of the introduction: 

"Now is definitely the time to jump on the CoffeeScript train, and you'll thank yourself for the time invested in learning about the language now, in lieu of the major time savings you'll make later."

"in lieu of" is not correct here, as it suggests the up-front investment is replacing later time savings. 

"Now is definitely the time to jump on the CoffeeScript train. The time you invest in learning about the language now will be repaid by major time savings later."

**Comment by maccman** [comment]
Fixed - thanks!
