### ISSUE TITLE
[Not exactly an issue] Japanese Translation

### ISSUE THREAD

**Issue by mnmly** [arcturo/library#14]
I translated the coffeescript book into Japanese, but I don't know how you handle translation.
Do you have any strategy on that? or can I just maintain it on my repo?
As it's my first translation on github, I don't even know how to contact the author for this kind of matter, sorry for posting on "Issue" :[

**Comment by maccman** [comment]
That is so awesome. Keep it in your repo for the moment (use gh-pages branch so it's hosted) and we'll figure out a way of merging it into this repository.

**Comment by mnmly** [comment]
I didn't know the gh-page branch thing. thanks a lot, I created the one :)
Yep, just let me know when you figure out how to settle.
