### ISSUE TITLE
mixin description error

### ISSUE THREAD

**Issue by lukeholder** [arcturo/library#25]
I think this is an error in the description of a mixin.

![imaget](http://lukeholder.net/share/The_Little_Book_on_CoffeeScript_-_Classes-20111105-094852.jpg)

I think mixins are easy in coffeescipt?

**Comment by maccman** [comment]
Mixins are easily supported by CoffeeScript, but aren't available natively. Seems right to me.

**Comment by lukeholder** [comment]
Sorry am i not reading this right?

"Mixins are not something supported natively by coffeescript."

This is false?

**Comment by maccman** [comment]
No, that is true. They key word there is 'natively' - mixins aren't part of the language's syntax.

**Comment by lukeholder** [comment]
https://github.com/arcturo/library/pull/26
